keyconfig_data = \
[("Window",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'pie.saveopen'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'pie.saveopen'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("name", 'pie.editor'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'pie.saveopen'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("name", 'pie.editor'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'pie.saveopen'),
       ],
      },
     ),
    ("wm.window_duplicate", {"type": 'W', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.read_homefile", {"type": 'N', "value": 'PRESS', "oskey": True}, None),
    ("wm.call_menu",
     {"type": 'O', "value": 'PRESS', "shift": True, "oskey": True},
     {"properties":
      [("name", 'INFO_MT_file_open_recent'),
       ],
      },
     ),
    ("wm.open_mainfile", {"type": 'O', "value": 'PRESS', "oskey": True}, None),
    ("wm.save_mainfile", {"type": 'S', "value": 'PRESS', "oskey": True}, None),
    ("wm.save_as_mainfile", {"type": 'S', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("wm.quit_blender", {"type": 'Q', "value": 'PRESS', "oskey": True}, None),
    ("wm.read_homefile", {"type": 'N', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_homefile", {"type": 'U', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'O', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'INFO_MT_file_open_recent'),
       ],
      },
     ),
    ("wm.open_mainfile", {"type": 'O', "value": 'PRESS', "ctrl": True}, None),
    ("wm.link", {"type": 'O', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.append", {"type": 'F1', "value": 'PRESS', "shift": True}, None),
    ("wm.save_mainfile", {"type": 'S', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_mainfile", {"type": 'W', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_as_mainfile", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.save_as_mainfile",
     {"type": 'S', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("copy", True),
       ],
      },
     ),
    ("wm.window_fullscreen_toggle", {"type": 'F11', "value": 'PRESS', "alt": True}, None),
    ("wm.quit_blender", {"type": 'Q', "value": 'PRESS', "ctrl": True}, None),
    ("wm.doc_view_manual_ui_context", {"type": 'F1', "value": 'PRESS', "alt": True}, None),
    ("wm.redraw_timer", {"type": 'T', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.debug_menu", {"type": 'D', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.search_menu", {"type": 'F', "value": 'PRESS', "oskey": True}, None),
    ("wm.call_menu",
     {"type": 'NDOF_BUTTON_MENU', "value": 'PRESS'},
     {"properties":
      [("name", 'USERPREF_MT_ndof_settings'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F2', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'VIEW_3D'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F3', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'NODE_EDITOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F4', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'CONSOLE'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F5', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'LOGIC_EDITOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F6', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'GRAPH_EDITOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F7', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'PROPERTIES'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F8', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'SEQUENCE_EDITOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F9', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'OUTLINER'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F10', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'IMAGE_EDITOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F11', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'TEXT_EDITOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'F12', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'area.type'),
       ("value", 'DOPESHEET_EDITOR'),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'user_preferences.inputs.ndof_sensitivity'),
       ("value", 1.1),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'user_preferences.inputs.ndof_sensitivity'),
       ("value", 0.9090909),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'user_preferences.inputs.ndof_sensitivity'),
       ("value", 1.5),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'user_preferences.inputs.ndof_sensitivity'),
       ("value", 0.6666667),
       ],
      },
     ),
    ("info.reports_display_update", {"type": 'TIMER_REPORT', "value": 'ANY', "any": True}, None),
    ("export_scene.fbx", {"type": 'E', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ],
   },
  ),
 ("Frames",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.frame_offset",
     {"type": 'LEFT_ARROW', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'RIGHT_ARROW', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("end", True),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True},
     {"properties":
      [("end", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'UP_ARROW', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'DOWN_ARROW', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_LAST', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_FIRST', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.animation_play",
     {"type": 'SPACE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("reverse", True),
       ],
      },
     ),
    ("screen.animation_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("screen.animation_play", {"type": 'MEDIA_PLAY', "value": 'PRESS'}, None),
    ("screen.animation_cancel", {"type": 'MEDIA_STOP', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'hops.vieport_submenu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'hops.material_list_menu'),
       ],
      },
     ),
    ("view3d.hops_helper_popup", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'hops_main_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'hops_main_pie'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'hops.vieport_submenu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'hops.material_list_menu'),
       ],
      },
     ),
    ("view3d.hops_helper_popup", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'hops_main_menu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'hops_main_pie'),
       ],
      },
     ),
    ("view3d.manipulator", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.manipulator", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.manipulator", {"type": 'LEFTMOUSE', "value": 'PRESS', "any": True}, None),
    ("view3d.cursor3d", {"type": 'ACTIONMOUSE', "value": 'PRESS'}, None),
    ("view3d.rotate", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("view3d.move", {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("view3d.zoom", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.view_selected",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_lock_to_active", {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_lock_clear", {"type": 'NUMPAD_PERIOD', "value": 'PRESS', "alt": True}, None),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom_camera_1_to_1", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "shift": True}, None),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_cursor", {"type": 'HOME', "value": 'PRESS', "alt": True}, None),
    ("view3d.view_center_pick", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'F4', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'F1', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'F2', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'F5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'F3', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'F1', "value": 'PRESS', "oskey": True}, None),
    ("view3d.viewnumpad", {"type": 'F2', "value": 'PRESS', "oskey": True}, None),
    ("view3d.viewnumpad", {"type": 'F3', "value": 'PRESS', "oskey": True}, None),
    ("view3d.view_pan",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'F6', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'F7', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'F6', "value": 'PRESS', "oskey": True}, None),
    ("view3d.viewnumpad", {"type": 'F7', "value": 'PRESS', "oskey": True}, None),
    ("view3d.localview", {"type": 'SPACE', "value": 'PRESS'}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True}, None),
    ("view3d.viewnumpad", {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True}, None),
    ("view3d.layers", {"type": 'ACCENT_GRAVE', "value": 'PRESS'}, None),
    ("view3d.layers", {"type": 'ONE', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'TWO', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'THREE', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'FOUR', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'FIVE', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'SIX', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'SEVEN', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'EIGHT', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'NINE', "value": 'PRESS', "any": True}, None),
    ("view3d.layers", {"type": 'ZERO', "value": 'PRESS', "any": True}, None),
    ("wm.context_toggle_enum",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.viewport_shade'),
       ("value_1", 'SOLID'),
       ("value_2", 'WIREFRAME'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'Z', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.viewport_shade'),
       ("value_1", 'SOLID'),
       ("value_2", 'MATERIAL'),
       ],
      },
     ),
    ("view3d.toggle_render", {"type": 'Z', "value": 'PRESS', "shift": True}, None),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ("center", False),
       ("enumerate", False),
       ("object", False),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ("center", False),
       ("enumerate", False),
       ("object", False),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ("center", True),
       ("enumerate", False),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ("center", False),
       ("enumerate", True),
       ("object", False),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ("deselect", False),
       ("toggle", True),
       ("center", True),
       ("enumerate", False),
       ("object", False),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ("center", True),
       ("enumerate", True),
       ("object", False),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ("center", False),
       ("enumerate", True),
       ("object", False),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ("center", True),
       ("enumerate", True),
       ("object", False),
       ],
      },
     ),
    ("view3d.select_border", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso", {"type": 'EVT_TWEAK_A', "value": 'ANY', "ctrl": True}, None),
    ("view3d.select_lasso", {"type": 'EVT_TWEAK_A', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap'),
       ],
      },
     ),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_set_enum",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'BOUNDING_BOX_CENTER'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'COMMA', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'MEDIAN_POINT'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'COMMA', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.use_pivot_point_align'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'SPACE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_manipulator'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'CURSOR'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'PERIOD', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'INDIVIDUAL_ORIGINS'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'PERIOD', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'ACTIVE_ELEMENT'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_S', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.select_orientation", {"type": 'SPACE', "value": 'PRESS', "alt": True}, None),
    ("transform.create_orientation",
     {"type": 'SPACE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("use", True),
       ],
      },
     ),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_element'),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("texture_space", True),
       ],
      },
     ),
    ("transform.resize",
     {"type": 'T', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("texture_space", True),
       ],
      },
     ),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'mops_main_menu'),
       ],
      },
     ),
    ("view3d.viewnumpad", {"type": 'F8', "value": 'PRESS'}, None),
    ("view3d.viewnumpad", {"type": 'F8', "value": 'PRESS', "oskey": True}, None),
    ("view3d.view_camera", {"type": 'F4', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'F3', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'F3', "value": 'PRESS', "oskey": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'F1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'F1', "value": 'PRESS', "oskey": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'F2', "value": 'PRESS', "oskey": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ],
   },
  ),
 ("Screen",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.animation_step", {"type": 'TIMER0', "value": 'ANY', "any": True}, None),
    ("screen.region_blend", {"type": 'TIMERREGION', "value": 'ANY', "any": True}, None),
    ("screen.screen_set",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.screen_set",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.screen_full_area", {"type": 'UP_ARROW', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screen_full_area", {"type": 'DOWN_ARROW', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screen_full_area", {"type": 'SPACE', "value": 'PRESS', "shift": True}, None),
    ("screen.screen_full_area",
     {"type": 'F10', "value": 'PRESS', "alt": True},
     {"properties":
      [("use_hide_panels", True),
       ],
      },
     ),
    ("screen.screenshot", {"type": 'F3', "value": 'PRESS', "ctrl": True}, None),
    ("screen.screencast", {"type": 'F3', "value": 'PRESS', "alt": True}, None),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("direction", 'NEXT'),
       ],
      },
     ),
    ("screen.space_context_cycle",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("direction", 'PREV'),
       ],
      },
     ),
    ("screen.region_quadview", {"type": 'F4', "value": 'PRESS', "oskey": True}, None),
    ("screen.repeat_history", {"type": 'F3', "value": 'PRESS'}, None),
    ("screen.repeat_last", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("screen.region_flip", {"type": 'F5', "value": 'PRESS'}, None),
    ("screen.redo_last", {"type": 'F6', "value": 'PRESS'}, None),
    ("script.reload", {"type": 'F8', "value": 'PRESS'}, None),
    ("file.execute", {"type": 'RET', "value": 'PRESS'}, None),
    ("file.execute", {"type": 'NUMPAD_ENTER', "value": 'PRESS'}, None),
    ("file.cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("ed.undo", {"type": 'Z', "value": 'PRESS', "oskey": True}, None),
    ("ed.redo", {"type": 'Z', "value": 'PRESS', "shift": True, "oskey": True}, None),
    ("ed.undo_history", {"type": 'Z', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("ed.undo", {"type": 'Z', "value": 'PRESS', "ctrl": True}, None),
    ("ed.redo", {"type": 'Z', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("ed.undo_history", {"type": 'Z', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("render.render",
     {"type": 'F12', "value": 'PRESS'},
     {"properties":
      [("use_viewport", True),
       ],
      },
     ),
    ("render.render",
     {"type": 'F12', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("animation", True),
       ("use_viewport", True),
       ],
      },
     ),
    ("render.view_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("render.view_show", {"type": 'F11', "value": 'PRESS'}, None),
    ("render.play_rendered_anim", {"type": 'F11', "value": 'PRESS', "ctrl": True}, None),
    ("screen.userpref_show", {"type": 'COMMA', "value": 'PRESS', "oskey": True}, None),
    ("screen.userpref_show", {"type": 'U', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ],
   },
  ),
 ("View2D",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("view2d.scroller_activate", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroller_activate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("view2d.pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view2d.scroll_right", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.scroll_left", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view2d.ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view2d.zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("view2d.zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("view2d.zoom", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("view2d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_right", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_left", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view2d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ("UV Editor",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_uv_sculpt'),
       ],
      },
     ),
    ("uv.mark_seam", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("uv.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("uv.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("uv.select_loop",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("uv.select_loop",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("uv.select_split", {"type": 'Y', "value": 'PRESS'}, None),
    ("uv.select_border",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("pinned", False),
       ],
      },
     ),
    ("uv.select_border",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("pinned", True),
       ],
      },
     ),
    ("uv.circle_select", {"type": 'C', "value": 'PRESS'}, None),
    ("uv.select_lasso",
     {"type": 'EVT_TWEAK_A', "value": 'ANY', "ctrl": True},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("uv.select_lasso",
     {"type": 'EVT_TWEAK_A', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("uv.select_linked",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("uv.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("uv.select_linked",
     {"type": 'L', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("uv.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("uv.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("uv.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("uv.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("uv.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("uv.select_pinned", {"type": 'P', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'IMAGE_MT_uvs_weldalign'),
       ],
      },
     ),
    ("uv.stitch", {"type": 'V', "value": 'PRESS'}, None),
    ("uv.pin",
     {"type": 'P', "value": 'PRESS'},
     {"properties":
      [("clear", False),
       ],
      },
     ),
    ("uv.pin",
     {"type": 'P', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear", True),
       ],
      },
     ),
    ("uv.unwrap", {"type": 'E', "value": 'PRESS'}, None),
    ("uv.minimize_stretch", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("uv.pack_islands", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("uv.average_islands_scale", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("uv.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("uv.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("uv.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("uv.cursor_set", {"type": 'ACTIONMOUSE', "value": 'PRESS'}, None),
    ("uv.tile_set", {"type": 'ACTIONMOUSE', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'IMAGE_MT_uvs_snap'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'IMAGE_MT_uvs_select_mode'),
       ],
      },
     ),
    ("wm.context_cycle_enum",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit_falloff'),
       ("wrap", True),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_S', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_uv_element'),
       ],
      },
     ),
    ("uv.export_layout",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("modified", True),
       ("opacity", 0.0),
       ],
      },
     ),
    ],
   },
  ),
 ("Image",
  {"space_type": 'IMAGE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("image.view_all", {"type": 'HOME', "value": 'PRESS'}, None),
    ("image.view_all",
     {"type": 'R', "value": 'PRESS', "oskey": True},
     {"properties":
      [("fit_view", True),
       ],
      },
     ),
    ("image.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("image.view_pan", {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("image.view_pan", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("image.view_pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("image.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("image.view_ndof", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("image.view_zoom_in", {"type": 'WHEELINMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'WHEELOUTMOUSE', "value": 'PRESS'}, None),
    ("image.view_zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("image.view_zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("image.view_zoom", {"type": 'LEFTMOUSE', "value": 'PRESS', "alt": True, "oskey": True}, None),
    ("image.view_zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("image.view_zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("image.view_zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 8.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 4.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("ratio", 2.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("ratio", 1.0),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.5),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_4', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.25),
       ],
      },
     ),
    ("image.view_zoom_ratio",
     {"type": 'NUMPAD_8', "value": 'PRESS'},
     {"properties":
      [("ratio", 0.125),
       ],
      },
     ),
    ("image.change_frame", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("image.sample", {"type": 'ACTIONMOUSE', "value": 'PRESS'}, None),
    ("image.curves_point_set",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("point", 'BLACK_POINT'),
       ],
      },
     ),
    ("image.curves_point_set",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("point", 'WHITE_POINT'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'OBJECT'),
       ("toggle", True),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 0),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 1),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 2),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FOUR', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 3),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'FIVE', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 4),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SIX', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 5),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'SEVEN', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 6),
       ],
      },
     ),
    ("wm.context_set_int",
     {"type": 'EIGHT', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.image.render_slots.active_index'),
       ("value", 7),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'CENTER'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'COMMA', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'MEDIAN'),
       ],
      },
     ),
    ("wm.context_set_enum",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("data_path", 'space_data.pivot_point'),
       ("value", 'CURSOR'),
       ],
      },
     ),
    ("image.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("image.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ],
   },
  ),
 ("Object Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("hops.slash", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("hops.bool_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("hops.bool_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("hops.mirror_mirror_z", {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.mirror_mirror_y", {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.mirror_mirror_x", {"type": 'X', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("btool.auto_intersect", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.auto_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.brush_to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_slice", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_inters", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_diff", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'OBJECT_MT_BoolTool_Menu'),
       ],
      },
     ),
    ("hops.slash", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("hops.bool_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("hops.bool_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("hops.mirror_mirror_z", {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.mirror_mirror_y", {"type": 'Y', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.mirror_mirror_x", {"type": 'X', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("btool.auto_subtract", {"type": 'MINUS', "value": 'PRESS'}, None),
    ("btool.auto_intersect", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.auto_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.auto_union", {"type": 'EQUAL', "value": 'PRESS'}, None),
    ("btool.to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("btool.brush_to_mesh", {"type": 'NUMPAD_ENTER', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_slice", {"type": 'NUMPAD_SLASH', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_inters", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_diff", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("btool.boolean_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'OBJECT_MT_BoolTool_Menu'),
       ],
      },
     ),
    ("wm.context_cycle_enum",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit_falloff'),
       ("wrap", True),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit_objects'),
       ],
      },
     ),
    ("view3d.game_start", {"type": 'P', "value": 'PRESS'}, None),
    ("object.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("object.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("object.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("object.select_linked", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("object.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("object.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'PARENT'),
       ("extend", True),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS'},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", False),
       ],
      },
     ),
    ("object.select_hierarchy",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("direction", 'CHILD'),
       ("extend", True),
       ],
      },
     ),
    ("object.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("object.parent_no_inverse_set", {"type": 'P', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.parent_clear", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("object.track_set", {"type": 'T', "value": 'PRESS', "ctrl": True}, None),
    ("object.track_clear", {"type": 'T', "value": 'PRESS', "alt": True}, None),
    ("object.constraint_add_with_targets", {"type": 'C', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.constraints_clear", {"type": 'C', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("object.location_clear",
     {"type": 'G', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.rotation_clear",
     {"type": 'R', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.scale_clear",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("clear_delta", False),
       ],
      },
     ),
    ("object.origin_clear", {"type": 'O', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_clear", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("object.hide_view_set",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("object.hide_render_clear", {"type": 'H', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("object.hide_render_set", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("object.move_to_layer", {"type": 'M', "value": 'PRESS'}, None),
    ("object.delete",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'X', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("use_global", False),
       ],
      },
     ),
    ("object.delete",
     {"type": 'DEL', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_global", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'INFO_MT_add'),
       ],
      },
     ),
    ("object.duplicates_make_real", {"type": 'A', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_object_apply'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_make_single_user'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'L', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_make_links'),
       ],
      },
     ),
    ("object.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.duplicate_move_linked", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("object.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("object.convert", {"type": 'C', "value": 'PRESS', "alt": True}, None),
    ("object.proxy_make", {"type": 'P', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("object.make_local", {"type": 'L', "value": 'PRESS'}, None),
    ("anim.keyframe_insert_menu", {"type": 'I', "value": 'PRESS'}, None),
    ("anim.keyframe_delete_v3d", {"type": 'I', "value": 'PRESS', "alt": True}, None),
    ("anim.keying_set_active_set", {"type": 'I', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("group.create", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("group.objects_remove", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("group.objects_remove_all", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("group.objects_add_active", {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("group.objects_remove_active", {"type": 'G', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_object_specials'),
       ],
      },
     ),
    ("object.data_transfer", {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ],
      },
     ),
    ("none", {"type": 'A', "value": 'PRESS'}, None),
    ("none", {"type": 'A', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'pie.delete'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'pie.delete'),
       ],
      },
     ),
    ("mesh.loopcut_slide", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.offset_edge_loops_slide", {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.poke", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("vertex_only", False),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("vertex_only", True),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("mesh.select_non_manifold", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.faces_select_linked_flat", {"type": 'F', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_mode'),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.spin", {"type": 'R', "value": 'PRESS', "alt": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.beautify_fill", {"type": 'F', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move", {"type": 'V', "value": 'PRESS'}, None),
    ("mesh.rip_move_fill", {"type": 'V', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("mesh.merge", {"type": 'M', "value": 'PRESS', "alt": True}, None),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS'}, None),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'INFO_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'ACTIONMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'ACTIONMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_occlude_geometry", False),
       ("only_selected", True),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_specials'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ],
      },
     ),
    ("wm.context_cycle_enum",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit_falloff'),
       ("wrap", True),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'CONNECTED'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'ONE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("use_extend", False),
       ("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'TWO', "value": 'PRESS', "oskey": True},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'THREE', "value": 'PRESS', "oskey": True},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ],
   },
  ),
 ("Object Non-modal",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.call_menu_pie",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("name", 'pie.objecteditmode'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'pie.animation'),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("mode", 'OBJECT'),
       ("toggle", True),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'OBJECT'),
       ("toggle", True),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("mode", 'OBJECT'),
       ("toggle", True),
       ],
      },
     ),
    ("object.mode_set",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'OBJECT'),
       ("toggle", True),
       ],
      },
     ),
    ("object.origin_set", {"type": 'C', "value": 'PRESS', "shift": True, "alt": True}, None),
    ],
   },
  ),
 ("Node Editor",
  {"space_type": 'NODE_EDITOR', "region_type": 'WINDOW'},
  {"items":
   [("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS'},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'ACTIONMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select",
     {"type": 'SELECTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_border",
     {"type": 'EVT_TWEAK_S', "value": 'ANY'},
     {"properties":
      [("tweak", True),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'EVT_TWEAK_A', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("node.select_lasso",
     {"type": 'EVT_TWEAK_A', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("node.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("node.link",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("detach", False),
       ],
      },
     ),
    ("node.link",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("detach", True),
       ],
      },
     ),
    ("node.resize", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("node.add_reroute", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("node.links_cut", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("node.select_link_viewer", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.backimage_move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("factor", 0.83333),
       ],
      },
     ),
    ("node.backimage_zoom",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("factor", 1.2),
       ],
      },
     ),
    ("node.backimage_fit", {"type": 'HOME', "value": 'PRESS', "alt": True}, None),
    ("node.backimage_sample", {"type": 'ACTIONMOUSE', "value": 'PRESS', "alt": True}, None),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("replace", False),
       ],
      },
     ),
    ("node.link_make",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("replace", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'NODE_MT_add'),
       ],
      },
     ),
    ("node.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("node.duplicate_move_keep_inputs", {"type": 'D', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("node.parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("node.detach", {"type": 'P', "value": 'PRESS', "alt": True}, None),
    ("node.join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("node.hide_toggle", {"type": 'H', "value": 'PRESS'}, None),
    ("node.mute_toggle", {"type": 'M', "value": 'PRESS'}, None),
    ("node.preview_toggle", {"type": 'H', "value": 'PRESS', "shift": True}, None),
    ("node.hide_socket_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("node.view_all", {"type": 'R', "value": 'PRESS', "oskey": True}, None),
    ("node.view_all", {"type": 'NDOF_BUTTON_FIT', "value": 'PRESS'}, None),
    ("node.view_selected", {"type": 'NUMPAD_PERIOD', "value": 'PRESS'}, None),
    ("node.select_border",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("tweak", False),
       ],
      },
     ),
    ("node.delete", {"type": 'X', "value": 'PRESS'}, None),
    ("node.delete", {"type": 'DEL', "value": 'PRESS'}, None),
    ("node.delete_reconnect", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("node.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("node.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("node.select_linked_to", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("node.select_linked_from", {"type": 'L', "value": 'PRESS'}, None),
    ("node.select_grouped",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("extend", False),
       ],
      },
     ),
    ("node.select_grouped",
     {"type": 'G', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("extend", True),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", False),
       ],
      },
     ),
    ("node.select_same_type_step",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "shift": True},
     {"properties":
      [("prev", True),
       ],
      },
     ),
    ("node.find_node", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_make", {"type": 'G', "value": 'PRESS', "ctrl": True}, None),
    ("node.group_ungroup", {"type": 'G', "value": 'PRESS', "alt": True}, None),
    ("node.group_separate", {"type": 'P', "value": 'PRESS'}, None),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS'},
     {"properties":
      [("exit", False),
       ],
      },
     ),
    ("node.group_edit",
     {"type": 'TAB', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("exit", True),
       ],
      },
     ),
    ("node.read_renderlayers", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("node.read_fullsamplelayers", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("node.render_changed", {"type": 'Z', "value": 'PRESS'}, None),
    ("node.clipboard_copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("node.clipboard_paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("node.clipboard_copy", {"type": 'C', "value": 'PRESS', "oskey": True}, None),
    ("node.clipboard_paste", {"type": 'V', "value": 'PRESS', "oskey": True}, None),
    ("node.viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("node.clear_viewer_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("node.translate_attach", {"type": 'G', "value": 'PRESS'}, None),
    ("node.translate_attach", {"type": 'EVT_TWEAK_A', "value": 'ANY'}, None),
    ("node.translate_attach", {"type": 'EVT_TWEAK_S', "value": 'ANY'}, None),
    ("transform.translate",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("release_confirm", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'EVT_TWEAK_A', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
      },
     ),
    ("transform.translate",
     {"type": 'EVT_TWEAK_S', "value": 'ANY'},
     {"properties":
      [("release_confirm", True),
       ],
      },
     ),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("node.move_detach_links", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("node.move_detach_links_release", {"type": 'EVT_TWEAK_A', "value": 'ANY', "alt": True}, None),
    ("node.move_detach_links", {"type": 'EVT_TWEAK_S', "value": 'ANY', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("data_path", 'tool_settings.snap_node_element'),
       ],
      },
     ),
    ],
   },
  ),
 ("View2D Buttons List",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("view2d.scroller_activate", {"type": 'LEFTMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroller_activate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view2d.pan", {"type": 'LEFTMOUSE', "value": 'PRESS', "oskey": True}, None),
    ("view2d.pan", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view2d.scroll_down", {"type": 'WHEELDOWNMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_up", {"type": 'WHEELUPMOUSE', "value": 'PRESS'}, None),
    ("view2d.scroll_down",
     {"type": 'PAGE_DOWN', "value": 'PRESS'},
     {"properties":
      [("page", True),
       ],
      },
     ),
    ("view2d.scroll_up",
     {"type": 'PAGE_UP', "value": 'PRESS'},
     {"properties":
      [("page", True),
       ],
      },
     ),
    ("view2d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view2d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view2d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view2d.zoom_out", {"type": 'NUMPAD_MINUS', "value": 'PRESS'}, None),
    ("view2d.zoom_in", {"type": 'NUMPAD_PLUS', "value": 'PRESS'}, None),
    ("view2d.reset", {"type": 'HOME', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Metaball",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("object.metaball_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("mball.reveal_metaelems", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mball.hide_metaelems",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mball.hide_metaelems",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mball.delete_metaelems", {"type": 'X', "value": 'PRESS'}, None),
    ("mball.delete_metaelems", {"type": 'DEL', "value": 'PRESS'}, None),
    ("mball.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("mball.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'TOGGLE'),
       ],
      },
     ),
    ("mball.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mball.select_similar", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("wm.context_cycle_enum",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit_falloff'),
       ("wrap", True),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'ENABLED'),
       ],
      },
     ),
    ("wm.context_toggle_enum",
     {"type": 'EVT_TWEAK_L', "value": 'ANY', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.proportional_edit'),
       ("value_1", 'DISABLED'),
       ("value_2", 'CONNECTED'),
       ],
      },
     ),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    import os
    from bpy_extras.keyconfig_utils import keyconfig_import_from_data
    keyconfig_import_from_data(os.path.splitext(os.path.basename(__file__))[0], keyconfig_data)
